### ISSUE TITLE
Custom "server.cfg" problem

### ISSUE THREAD

**Issue by Zero-Tolerance** [spezifanta/hldm-docker#7]
I'm launching the server as indicated in the guide with the parameter:
"-v gamedir:/gamedir"
I've created a directory called "gamedir," and it's located here:
"/home/user/gamedir"
Inside, there's a test "cfg.cfg" file that I'm attempting to execute ("exec cfg.cfg") from the server console, but the server doesn't seem to recognize it (!). What am I doing wrong? I'm launching the server from the directory "/home/user".

I noticed an echo-output left by spezifanta regarding the custom "server.cfg" at:
"/opt/steam/hldm/valve/config"
I created this path, but the server doesn't recognize the files in it either.

**Comment by cngil** [comment]
To execute a custom server.cfg file, you need to mount a volume to "/opt/steam/hldm/valve/config" as indicated in the logs when starting the container.

You can achieve this by using the following Docker run command:

```bash
docker run -it --rm -d -p 27015:27015 -p 27015:27015/udp -v /path/to/local/dir:/opt/steam/hldm/valve/config spezifanta/hldm
```

or

Create a [docker-compose.yml](https://github.com/spezifanta/hldm-docker/blob/master/docker-compose.yml) file with this volume mounted.

**Comment by cngil** [comment]
To execute a custom server.cfg file, you need to **mount a volume to "/opt/steam/hldm/valve/config"** as indicated in the logs when starting the container.

You can achieve this by creating a [docker-compose.yml](https://github.com/spezifanta/hldm-docker/blob/master/docker-compose.yml) file with this volume mounted or using the following Docker run command:

```bash
docker run -it --rm -d -p 27015:27015 -p 27015:27015/udp -v /path/to/local/dir:/opt/steam/hldm/valve/config spezifanta/hldm
```
